### ISSUE TITLE
use nunjucks template on browser side

### ISSUE THREAD

**Issue by bmaz** [medialab/resin-annuaire#14]

**Comment by bmaz** [comment]
@Yomguithereal is it precompiled as recommended in https://mozilla.github.io/nunjucks/api.html#recommended-setups ?

**Comment by bmaz** [comment]
Warning: Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/
Maybe I should use nunjucks.render asynchronously: https://mozilla.github.io/nunjucks/api.html#asynchronous

**Comment by boogheta** [comment]
Ha I didn't realise your xmlhttprequest was synchronous, async would be better indeed (otherwise it basically freezes your browser during the load)
