### ISSUE TITLE
#Page - fiches perso

### ISSUE THREAD

**Issue by MarionFrelat** [medialab/resin-annuaire#6]
On aimerait voir apparaitre ces informations : 

![fiche_profil_annuaire](https://github.com/medialab/resin-annuaire/assets/5666046/06ad702a-1af8-472a-9176-250c96a3bc6f)

--------------------------------------
Photo (format rond ou carré ; avatar non genré si non renseigné)
Prénom Nom
Phrase de présentation courte  (italique, entre guillemets)
Genre: **Le genre**
----------------------------------------
Contact : 
**Structure(s) de rattachement**
**Pays**
**Ville**
**Email pro (sans le @)**
**Téléphone pro**
**Langues parlées** 
------------------------------------------
**Biographie libre**

**Compétences**

Fonction/titre 

**Lien vers page perso :** url "lien vers page personnelle"
**Lien vers page pro :** url "lien vers page professionnelle"  
**Productions** : titre (souligné), url "lien vers la production" 
**Formations :** titre (gras), date, description
**Autres activités :** titre (gras), date, description
**Responsabilités :** titre (gras), date, description
**Distinctions :** titre (gras), date, description

En bas de la fiche : 
"Pour mettre à jour votre présentation, veuillez envoyer un mail à annuaire.ingenieurs@sciencespo.fr (sans le @), nous ne manquerons pas de faire les modifications dans les plus brefs délais"

- Les champs qui n'ont pas été remplis sur le formulaire ne doivent pas apparaitre sur la fiche

**Comment by bmaz** [comment]
- [ ] Button should be clickable
- [ ] Add edit link
- [ ]
